# Generated by Django 2.0.6 on 2018-06-27 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locking', '0003_auto_20160907_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lock',
            name='_locked_by',
            field=models.ForeignKey(db_column='locked_by', editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='working_on_locking_lock', to=settings.AUTH_USER_MODEL),
        ),
    ]
